# cloudrun.yaml
# Cloud Run 배포용 예시 YAML (gcloud CLI 또는 Cloud Build에서 사용)

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: voice-clone-api
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: asia-northeast3-docker.pkg.dev/voicecloning-467122/voice-clone-api/voice-clone-api:latest
          env:
            - name: GCS_BUCKET_NAME
              value: "voice-storage-asia3-seungbum1"
            - name: VERTEX_PROJECT
              value: "voicecloning-467122"
            - name: VERTEX_LOCATION
              value: "asia-northeast3"
            - name: VERTEX_JOB_NAME
              value: "xtts-job-v1"
            - name: VERTEX_JOB_IMAGE_URI
              value: "asia-northeast3-docker.pkg.dev/voicecloning-467122/vertex-job/vertex-job:latest"
          ports:
            - containerPort: 8080
      timeoutSeconds: 300